version: '3.7'

services:
  client:
    image: in2code/httpd:2.4-alpine
    volumes:
      - ./client/:/app/:cached
      - client-var:/app/var/:nocopy
    environment:
      WEB_SERVER_NAME: client.t3am.docker
      WEB_PHP_SERVICE: client-php
  client-php:
    image: in2code/php:7.2-fpm
    volumes:
      - ./client/:/app/
      - client-var:/app/var/:nocopy
  client-mysql:
    image: in2code/mysql:5.7
    volumes:
      - client-mysql:/var/lib/docker/:cached
      - $HOME/.composer/auth.json:/tmp/composer/auth.json
      - $HOME/.composer/cache/:/tmp/composer/cache/
    environment:
      MYSQL_DATABASE: client
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root

  client8:
    image: in2code/httpd:2.4-alpine
    volumes:
      - ./client8/:/app/:cached
      - client8-var:/app/var/:nocopy
    environment:
      WEB_SERVER_NAME: client.t3am.docker
      WEB_PHP_SERVICE: client-php
  client8-php:
    image: in2code/php:7.2-fpm
    volumes:
      - ./client8/:/app/
      - client8-var:/app/var/:nocopy
  client8-mysql:
    image: in2code/mysql:5.7
    volumes:
      - client-mysql:/var/lib/docker/:cached
      - $HOME/.composer/auth.json:/tmp/composer/auth.json
      - $HOME/.composer/cache/:/tmp/composer/cache/
    environment:
      MYSQL_DATABASE: client8
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root

  server:
    image: in2code/httpd:2.4-alpine
    volumes:
      - ./server/:/app/:cached
      - server-var:/app/var/:nocopy
    links:
      - server-php:php
    environment:
      WEB_SERVER_NAME: server.t3am.docker
      WEB_PHP_SERVICE: server-php
  server-php:
    image: in2code/php:7.2-fpm
    volumes:
      - ./server/:/app/:cached
      - server-var:/app/var/:nocopy
      - $HOME/.composer/auth.json:/tmp/composer/auth.json
      - $HOME/.composer/cache/:/tmp/composer/cache/
  server-mysql:
    image: in2code/mysql:5.7
    volumes:
      - server-mysql:/var/lib/docker/
    environment:
      MYSQL_DATABASE: server
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root

volumes:
  client-mysql:
  client-var:
  client8-var:
  client8-mysql:
  server-mysql:
  server-var:
